### ISSUE TITLE
nv_wavenet_test.py fails with a larger than one batch size

### ISSUE THREAD

**Issue by PetrochukM** [NVIDIA/nv-wavenet#14]
## Issue description

Running ``nv_wavenet_test.py`` with an increased batch size causes an error.

## Offending Code
```
    model = torch_load("model.pt", torch.device('cuda'))
    wavenet = nv_wavenet.NVWaveNet(**model)
    cond_input = torch_load("cond_input.pt", torch.device('cuda'))
    cond_input = cond_input.repeat(1, 2, 1, 1)  # Increase the batch size to 2

    samples = wavenet.infer(cond_input, nv_wavenet.Impl.AUTO)
```

## Error

`GPUassert: invalid argument ../nv_wavenet.cuh 547`

## System Info

PyTorch version: 0.4.0
Python version: 3.6.4
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-7a90c013.so.7.0.5
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudnn-3f9a723f.so.6.0.21

**Comment by RPrenger** [comment]
@PetrochukM I have added a PR that fixes the issue.  I had forgotten to add the batch dimension in the output.  The rest of the test will fail in the Python code because the Wave writing code is expecting a 1-d Tensor

**Comment by PetrochukM** [comment]
Submitted a PR to fix tests: https://github.com/NVIDIA/nv-wavenet/pull/17
