### ISSUE TITLE
residual layer should be one shorter

### ISSUE THREAD

**Issue by zhf459** [NVIDIA/nv-wavenet#20]
great work !It seems every layer has a residual weight-bias, skip weight-bias, dilate weight-bias, why the model require `residual weights/biases lists should be one shorter`? actually you append a zero-weights/biases rather than use the trained model's residual weights/biases.

**Comment by RPrenger** [comment]
Hi @zhf459 .  We add the dummy tensor because the nv-wavenet CUDA code expects there to be as many residual weights as there are dilated and skip weights, but it throws away the result of the last residual layer.  I didn't want users to have to input a dummy tensor themselves.

**Comment by zhf459** [comment]
thank you, i see.Another problem is about `use_tanh_embed`. is it used in reference ,I find it used in [in this function](https://github.com/NVIDIA/nv-wavenet/blob/901e48b7479ca2f0dfc995347f1375a2943106fc/nv_wavenet_reference.cpp#L42).

**Comment by RPrenger** [comment]
I'm not sure I understand the question.  In the model you can download on the page we use `use_tanh_embed=False`.  The original DeepVoice implementation used `use_tanh_embed=True`

**Comment by RPrenger** [comment]
I'm going to request this issue be closed.  @zhf459 If you have further questions feel free to contact me or open another issue.

**Comment by zhf459** [comment]
@RPrenger ok~,thanks!
