### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by glennglennglenn** [NVIDIA/nv-wavenet#24]
Does anyone know why I can't build the project?

ubuntu@ip-172-31-18-152:~/nv-wavenet$ cd pytorch; make
nvcc -arch=sm_37 -std=c++11  --use_fast_math -lineinfo -maxrregcount 128 -I .. wavenet_infer.cu ../matrix.cpp -lz -Xcompiler -fPIC -shared -o wavenet_infer.so 
../nv_wavenet_util.cuh(89): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

../nv_wavenet_util.cuh(89): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

2 errors detected in the compilation of "/tmp/tmpxft_00004edd_00000000-8_wavenet_infer.cpp1.ii".
Makefile:48: recipe for target 'wavenet_infer' failed
make: *** [wavenet_infer] Error 1

**Comment by PetrochukM** [comment]
Please take a look at this issue: https://github.com/NVIDIA/nv-wavenet/issues/5

**Comment by glennglennglenn** [comment]
Thanks @PetrochukM Do you know if it is possible to build with Cuda 8.0?

**Comment by BrianPharris** [comment]
nv-wavenet is only supported on CUDA 9.0 and later.
