### ISSUE TITLE
GPUAssert raised during inference at cudaLaunchCooperativeKernel() on GTX 1080 Ti

### ISSUE THREAD

**Issue by sdorminey** [NVIDIA/nv-wavenet#27]
Testing with nv_wavenet_test.py succeeds (congrats on the remarkable speed!) and training in distributed mode goes swiftly, 10k+ iters in. inference.py fails though, asserting on kernel launch. How should I proceed?

## System info
Driver version: 396.24
Kernel: Linux safpa 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
GPUs: 2x GeForce GTX 1080 Ti

## Error
mabel@safpa:~/git/nv-wavenet/pytorch$ python3 inference.py -f mel_files.txt -c checkpoints/wavenet_10000 -o .
arctic_a0001.wav.pt
57 blocks, 2 blocks per SM
GPUassert: too many blocks in cooperative launch ../nv_wavenet_persistent.cuh *530*
python3: wavenet_infer.cu:97: void infer(std::shared_ptr<nvWavenetInfer<float, float, 64, 256, 256> >, float*, int*, int, int): Assertion `wavenet->run(sample_count, batch_size, samples, batch_size_per_block, true)' failed.
Abortita (nekropsio elŝutita)

## Line 530 of nv_wavenet_persistent.cuh:
    cudaError_t code = cudaLaunchCooperativeKernel((void*)nv_wavenet_persistent<T_weight,T_data,R,S,A,BATCH_UNROLL>, grid, block, &p_params, 0, stream);
    gpuAssert(code, __FILE__, __LINE__, false);

Thanks!

**UPDATE:** Issue seems to be only with the Persistent implementation. Using: `python3 inference.py -f mel_files.txt -c checkpoints/wavenet_10000 -o . -i dual` I was able to run without issue. Would love to use Persistent though, if supported by my hardware!

**Comment by BrianPharris** [comment]
Hi @sdorminey - since the persistent implementation loads all weights persistently into the register file, the size of the model that you can run is limited by the size of your GPU.  The model as currently implemented requires 57 blocks, and can fit 2 blocks per SM -- suggesting that you need 29 SMs.  Since a GTX 1080 Ti has 20 SMs, this leads to the "too many blocks in cooperative launch" assertion.

**Comment by nartes** [comment]
How many SMs does Tesla T4 have? Is there any available cli tool to estimate it. What is SM? Is there any link to a definition? Thanks!

**UPD**:
Perhaps, this link does explain the issue - http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
