### ISSUE TITLE
Expected Performance on Geforce 10 Series GPUs?

### ISSUE THREAD

**Issue by richardmcai** [NVIDIA/nv-wavenet#41]
I've been testing the performance on a 1070 and 1080 Ti on two separate machines, both running Ubuntu 16.04 with driver 384.130, and the results I'm getting are dramatically worse than the ones shown in the blog or here https://github.com/NVIDIA/nv-wavenet/issues/18, with both GPUs performing at about 4.3khz and 6.3khz for the single-block and dual-block implementations respectively for the 20-layer medium network. Is this to be expected from Geforce 10 series GPUs or is there a possible configuration issue that is slowing performance?

**Comment by BrianPharris** [comment]
@richardmcai are you running FP16 or FP32 precision?  Geforce 10 GPUs do not have full-rate fp16 support.

**Comment by richardmcai** [comment]
Thank you, I think that fixed it. These are the results I'm getting now:

 | | Single Block | Dual Block
------------ | ------------ | ------------ 
1070 | 12.22 | 15.65
1080 Ti | 12.89 | 17.10

Which is comparable to the results from https://github.com/NVIDIA/nv-wavenet/issues/18.

**Comment by MotorCityCobra** [comment]
@richardmcai how did you install for a 1080?  
The make file won't install without this 'ARCH' value and I'm not sure the 10 series has whatever this is.
