### ISSUE TITLE
Is it possible to do re-training or fine-tune in this code ?

### ISSUE THREAD

**Issue by rishikksh20** [NVIDIA/nv-wavenet#47]
I want to do transfer learning, is it possible to do using its code? If yes then how nothing mentioned in README about re-training or fine-tune.

**Comment by gsoul** [comment]
What task would you like to "transfer-learn" this model?

**Comment by rishikksh20** [comment]
@gsoul I want to train this model on Indian voice, but I don't want to train the model from scratch. Instead, I want to re-train this model using pre-trained weights on Indian English Voice dataset.

**Comment by gsoul** [comment]
Well, theoretically you could do that:
https://github.com/NVIDIA/nv-wavenet/blob/master/pytorch/config.json#L9

but given that you would need to retrain not only WaveNet, but also Tacotron model, I have some doubts on how well would that work. But of course, you never know until you try it.
