### ISSUE TITLE
train with tacotron2(nvidia)

### ISSUE THREAD

**Issue by viogoes** [NVIDIA/nv-wavenet#49]
HI:
   i want to train nv-wavenet with tacotron2 mel_outputs_postnet but  mel_outputs_postnet size is not equals with mel_spectrogram from audio  . How do i  align  mel_outputs_postnet  and  audio.
Please help. Thanks!

**Comment by gsoul** [comment]
Please show your code, so it'd be easier to understand what you're trying to achieve. Overall I believe that mel_outputs_postnet is a 3D tensor while mel_spectrogram is expected to be 2D...

**Comment by fxwderrick** [comment]
@viogoes did you solve this problem of mismatching size? I found that the audio quality is not satisfying when tacotron2(nvidia) and nv-wavenet are trained seperately on the ground truth mel-spectrogram. According to the paper of tacotron2, I think it will be better to train nv-wavenet based on the predicted mel-spectrogram of tacotron2. However, the shape alignment is a big problem here.
