### ISSUE TITLE
Invalid Device Function with CUDA 9.0 and Geforce Titan X

### ISSUE THREAD

**Issue by tomse-h** [NVIDIA/nv-wavenet#71]
I am trying to use my Geforce Titan X to run the test provided. However, with the given sm_70, and also sm_60 it results in _GPUassert: invalid device function nv_wavenet_util.cuh 48_
Also, when I try to use sm_52, as this is the given compute capability, I run into different errors.

May my card is not be supported at all? I'd appreciate any help, if possible.

**Comment by isaacleeai** [comment]
fixed simply by giving 4 as arguement for function wavenet_infer in file wavenet_infer.cu
