### ISSUE TITLE
Why use assembly for "isNegativeZero"?

### ISSUE THREAD

**Issue by isaacleeai** [NVIDIA/nv-wavenet#79]
Hi,

Is there a reason why you used assembly for "isNegativeZero"? Is it for performence? Also, is there a good source on PTX assembly to figure out what is actually going on in the function ( Nvidia's developer's guide has been down for a few days )?

Thanks

**Comment by BrianPharris** [comment]
Yes, it's a performance enhancement -- I'm not sure how to express the half form of negative zero as a literal, which means I had to do a float2half conversion of -0f before the comparison.  The inline assembly makes that conversion unnecessary.
