### ISSUE TITLE
What are the requirements for nv-wavenet?

### ISSUE THREAD

**Issue by erogol** [NVIDIA/nv-wavenet#8]
Could you please specify what version of CUDA and other (if needed) libraries necessary to run nv-wavenet?     

P.S. Thx for this great tool! I like to integrate it to https://github.com/mozilla/TTS

**Comment by BrianPharris** [comment]
nv-wavenet requires CUDA 9.0 or later.  The PyTorch wrapper has been tested on PyTorch 0.4, and the pytorch test script depends on numpy and scipy.  There are no other dependencies.

I hope it's useful to you!
