### ISSUE TITLE
Unconditional generation?

### ISSUE THREAD

**Issue by khiner** [NVIDIA/nv-wavenet#91]
Can anyone provide guidance as to the best way to use or modify nv-wavenet to generate audio unconditionally?

Thank you!

**Comment by chaonan99** [comment]
You can create zero matrix instead of calculating mel spec [here](https://github.com/NVIDIA/nv-wavenet/blob/master/pytorch/mel2samp_onehot.py#L69):

```python
def get_mel(self, audio):
    return torch.zeros((80, audio.shape[0]//self.hop_length+1))
```

**Comment by khiner** [comment]
Great, that makes sense, thanks!
